# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byn < Formula
  desc "Local-first secure secrets vault and credential manager."
  homepage "https://github.com/sandeepbaynes/byn"
  version "0.5.5"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.5.5/byn-darwin-amd64.tar.gz"
      sha256 "0628adde2419cb559d0d231827988b39a02daf56e938d7cb9e3e81b9ae703a53"

      define_method(:install) do
        bin.install "byn"
        bin.install "byn-exec-helper"
        man1.install "man/byn.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.5.5/byn-darwin-arm64.tar.gz"
      sha256 "7bf971d781a7fc952d6758892cc7bcb3ec2a845563837a7cbaf869cd4748ed31"

      define_method(:install) do
        bin.install "byn"
        bin.install "byn-exec-helper"
        man1.install "man/byn.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.5.5/byn-linux-amd64.tar.gz"
      sha256 "a0c96f2fd32d94c728562a2b62021e6d7f3cb968b25d087da371be21d238b1a2"
      define_method(:install) do
        bin.install "byn"
        bin.install "byn-exec-helper"
        man1.install "man/byn.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.5.5/byn-linux-arm64.tar.gz"
      sha256 "2a815f1bf6e444515228aa7b63b02573ebf79a79e1a186e7bbfd313ef4befca6"
      define_method(:install) do
        bin.install "byn"
        bin.install "byn-exec-helper"
        man1.install "man/byn.1"
      end
    end
  end

  test do
    assert_match "byn #{version}", shell_output("#{bin}/byn version")
  end
end
