# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byn < Formula
  desc "Local-first secure secrets vault and credential manager."
  homepage "https://github.com/sandeepbaynes/byn"
  version "0.0.1"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.0.1/byn-darwin-amd64"
      sha256 "56f80b61096a47289272094352b37352ce11d52ef33c4948c91226203bae9c01"

      define_method(:install) do
        bin.install "byn-darwin-amd64" => "byn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.0.1/byn-darwin-arm64"
      sha256 "0cf50d6bf5243d26b83780c389e481da2ff1c2cffd419d1f3c578cb4cd7de76d"

      define_method(:install) do
        bin.install "byn-darwin-arm64" => "byn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.0.1/byn-linux-amd64"
      sha256 "e3eac1c99542bfb7d24c3d948997571cf2277226b7a2e75bb7146308050bd87b"
      define_method(:install) do
        bin.install "byn-linux-amd64" => "byn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.0.1/byn-linux-arm64"
      sha256 "56e94bed82b54c574cf589405cb5a783944933490d0ffa00cc9a17b2f5bfe33a"
      define_method(:install) do
        bin.install "byn-linux-arm64" => "byn"
      end
    end
  end

  test do
    assert_match "byn #{version}", shell_output("#{bin}/byn version")
  end
end
