# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byn < Formula
  desc "Local-first secure secrets vault and credential manager."
  homepage "https://github.com/sandeepbaynes/byn"
  version "0.2.0"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.2.0/byn-darwin-amd64.tar.gz"
      sha256 "f9be7ca73b6e34ad096e4c7e2edc7b07c79bc15a7c2996c67dff27566faba7ca"

      define_method(:install) do
        bin.install "byn"
        man1.install "man/byn.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.2.0/byn-darwin-arm64.tar.gz"
      sha256 "b260958c88f816d2c5c85b918ea908a8610ae9208af4d926bc480f530330f642"

      define_method(:install) do
        bin.install "byn"
        man1.install "man/byn.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.2.0/byn-linux-amd64.tar.gz"
      sha256 "a508899701a13e83b6a8b79aae72cb32be9ce232a3e33c4b2e7b74e88f5430ac"
      define_method(:install) do
        bin.install "byn"
        man1.install "man/byn.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandeepbaynes/byn/releases/download/v0.2.0/byn-linux-arm64.tar.gz"
      sha256 "3cb158153c0095fbd61547f3f3628e91b83bc8e89a2115147483fbbb1ef0e804"
      define_method(:install) do
        bin.install "byn"
        man1.install "man/byn.1"
      end
    end
  end

  test do
    assert_match "byn #{version}", shell_output("#{bin}/byn version")
  end
end
